package object.card;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

interface DeckCardID {

    int
            ONE_UP_1 = 1,
            ONE_UP_2 = 2,
            BOMB_1 = 3,
            BOMB_2 = 4,
            BOMB_3 = 5,
            BOMB_4 = 6,
            BORROW_1 = 7,
            BORROW_2 = 8,
            CAPTURE_SPELLCARD = 9,
            FOCUS_1 = 10,
            FOCUS_2 = 11,
            GRAZE_1 = 12,
            GRAZE_2 = 13,
            GRAZE_3 = 14,
            GRAZE_4 = 15,
            GRAZE_5 = 16,
            GRAZE_6 = 17,
            GRAZE_7 = 18,
            GRAZE_8 = 19,
            GRAZE_9 = 20,
            GRAZE_10 = 21,
            GRAZE_11 = 22,
            GRAZE_12 = 23,
            GRAZE_13 = 24,
            GRAZE_14 = 25,
            GRIMOIRE_1 = 26,
            GRIMOIRE_2 = 27,
            KOURINDOU = 28,
            LASER_SHOT = 29,
            LAST_WORLD = 30,
            MASTER_PLAN = 31,
            MELEE = 32,
            MINI_HAKKERO = 33,
            PARTY = 34,
            POWER_1 = 35,
            POWER_2 = 36,
            POWER_3 = 37,
            POWER_4 = 38,
            POWER_5 = 39,
            POWER_6 = 40,
            SEAL_AWAY_1 = 41,
            SEAL_AWAY_2 = 42,
            SEAL_AWAY_3 = 43,
            SEAL_AWAY_4 = 44,
            SHOOT_1 = 45,
            SHOOT_2 = 46,
            SHOOT_3 = 47,
            SHOOT_4 = 48,
            SHOOT_5 = 49,
            SHOOT_6 = 50,
            SHOOT_7 = 51,
            SHOOT_8 = 52,
            SHOOT_9 = 53,
            SHOOT_10 = 54,
            SHOOT_11 = 55,
            SHOOT_12 = 56,
            SHOOT_13 = 57,
            SHOOT_14 = 58,
            SHOOT_15 = 59,
            SHOOT_16 = 60,
            SHOOT_17 = 61,
            SHOOT_18 = 62,
            SHOOT_19 = 63,
            SHOOT_20 = 64,
            SHOOT_21 = 65,
            SHOOT_22 = 66,
            SHOOT_23 = 67,
            SHOOT_24 = 68,
            SORCERERS_SUTRA_SCROLL = 69,
            SPIRITUAL_ATTACK_1 = 70,
            SPIRITUAL_ATTACK_2 = 71,
            SPIRITUAL_ATTACK_3 = 72,
            SPIRITUAL_ATTACK_4 = 73,
            SPIRITUAL_ATTACK_5 = 74,
            SPIRITUAL_ATTACK_6 = 75,
            STOPWATCH = 76,
            SUPERNATURAL_BORDER_1 = 77,
            SUPERNATURAL_BORDER_2 = 78,
            TEMPEST = 79,
            VOILE = 80,
            ERASE_SHOT_1 = 81,
            ERASE_SHOT_2 = 82,
            ERASE_SHOT_3 = 83,
            ERASE_SHOT_4 = 84,
            ERASE_SHOT_5 = 85,
            ERASE_SHOT_6 = 86,
            ERASE_SHOT_7 = 87,
            ERASE_SHOT_8 = 88,
            ERASE_SHOT_9 = 89,
            NIMBLE_CLOTH_1 = 90,
            NIMBLE_CLOTH_2 = 91,
            OCCULT_BALL_1 = 92,
            OCCULT_BALL_2 = 93,
            PURIFICATION = 94,
            REVENGE_SHOT_1 = 95,
            REVENGE_SHOT_2 = 96,
            REVENGE_SHOT_3 = 97,
            REVENGE_SHOT_4 = 98,
            SPELL_ASSIST_1 = 99,
            SPELL_ASSIST_2 = 100;

    Set<Integer>
            ONE_UP_CARD = new HashSet<>(Arrays.asList(ONE_UP_1, ONE_UP_2)),
            BOMB_CARD = new HashSet<>(Arrays.asList(BOMB_1, BOMB_2, BOMB_3, BOMB_4)),
            BORROW_CARD = new HashSet<>(Arrays.asList(BORROW_1, BORROW_2)),
            CAPTURE_SPELLCARD_CARD = new HashSet<>(Collections.singletonList(CAPTURE_SPELLCARD)),
            FOCUS_CARD = new HashSet<>(Arrays.asList(FOCUS_1, FOCUS_2)),
            GRAZE_CARD = new HashSet<>(Arrays.asList(GRAZE_1, GRAZE_2, GRAZE_3, GRAZE_4, GRAZE_5, GRAZE_6, GRAZE_7, GRAZE_8,
                    GRAZE_9, GRAZE_10, GRAZE_11, GRAZE_12, GRAZE_13, GRAZE_14)),
            GRIMOIRE_CARD = new HashSet<>(Arrays.asList(GRIMOIRE_1, GRIMOIRE_2)),
            KOURINDOU_CARD = new HashSet<>(Collections.singletonList(KOURINDOU)),
            LASER_SHOT_CARD = new HashSet<>(Collections.singletonList(LASER_SHOT)),
            LAST_WORLD_CARD = new HashSet<>(Collections.singletonList(LAST_WORLD)),
            MASTER_PLAN_CARD = new HashSet<>(Collections.singletonList(MASTER_PLAN)),
            MELEE_CARD = new HashSet<>(Collections.singletonList(MELEE)),
            MINI_HAKKERO_CARD = new HashSet<>(Collections.singletonList(MINI_HAKKERO)),
            PARTY_CARD = new HashSet<>(Collections.singletonList(PARTY)),
            POWER_CARD = new HashSet<>(Arrays.asList(POWER_1, POWER_2, POWER_3, POWER_4, POWER_5, POWER_6)),
            SEAL_AWAY_CARD = new HashSet<>(Arrays.asList(SEAL_AWAY_1, SEAL_AWAY_2, SEAL_AWAY_3, SEAL_AWAY_4)),
            SHOOT_CARD = new HashSet<>(Arrays.asList(SHOOT_1, SHOOT_2, SHOOT_3, SHOOT_4, SHOOT_5, SHOOT_6, SHOOT_7, SHOOT_8, SHOOT_9
                    , SHOOT_10, SHOOT_11, SHOOT_12, SHOOT_13, SHOOT_14, SHOOT_15, SHOOT_16, SHOOT_17, SHOOT_18, SHOOT_19, SHOOT_20
                    , SHOOT_21, SHOOT_22, SHOOT_23, SHOOT_24)),
            SORCERERS_SUTRA_SCROLL_CARD = new HashSet<>(Collections.singletonList(SORCERERS_SUTRA_SCROLL)),
            SPIRITUAL_ATTACK_CARD = new HashSet<>(Arrays.asList(SPIRITUAL_ATTACK_1, SPIRITUAL_ATTACK_2, SPIRITUAL_ATTACK_3,
                    SPIRITUAL_ATTACK_4, SPIRITUAL_ATTACK_5, SPIRITUAL_ATTACK_6)),
            STOPWATCH_CARD = new HashSet<>(Collections.singletonList(STOPWATCH)),
            SUPERNATURAL_BORDER_CARD = new HashSet<>(Arrays.asList(SUPERNATURAL_BORDER_1, SUPERNATURAL_BORDER_2)),
            TEMPEST_CARD = new HashSet<>(Collections.singletonList(TEMPEST)),
            VOILE_CARD = new HashSet<>(Collections.singletonList(VOILE)),
            ERASE_SHOT_CARD = new HashSet<>(Arrays.asList(ERASE_SHOT_1, ERASE_SHOT_2, ERASE_SHOT_3, ERASE_SHOT_4, ERASE_SHOT_5
                    , ERASE_SHOT_6, ERASE_SHOT_7, ERASE_SHOT_8, ERASE_SHOT_9)),
            NIMBLE_CLOTH_CARD = new HashSet<>(Arrays.asList(NIMBLE_CLOTH_1, NIMBLE_CLOTH_2)),
            OCCULT_BALL_CARD = new HashSet<>(Arrays.asList(OCCULT_BALL_1, OCCULT_BALL_2)),
            PURIFICATION_CARD = new HashSet<>(Collections.singletonList(PURIFICATION)),
            REVENGE_SHOT_CARD = new HashSet<>(Arrays.asList(REVENGE_SHOT_1, REVENGE_SHOT_2, REVENGE_SHOT_3, REVENGE_SHOT_4)),
            SPELL_ASSIST_CARD = new HashSet<>(Arrays.asList(SPELL_ASSIST_1, SPELL_ASSIST_2));
}
