package object.card;

interface LunaticExtraCardID {

    int
            ONE_UP_1 = 1,
            ONE_UP_2 = 2,
            BOMB_1 = 3,
            BOMB_2 = 4,
            BOMB_3 = 5,
            BOMB_4 = 6,
            CAPTURE_SPELLCARD_1 = 7,
            CAPTURE_SPELLCARD_2 = 8,
            FOCUS = 9,
            FULL_POWER = 10,
            GHOST_LANTERN = 11,
            GIFT_OF_YATAGARASE_1 = 12,
            GIFT_OF_YATAGARASE_2 = 13,
            HOURAI_ELIXIR = 14,
            INTERRUPT_1 = 15,
            INTERRUPT_2 = 16,
            JEWELED_PAGODA = 17,
            LASET_SHOT_1 = 18,
            LASET_SHOT_2 = 19,
            MASTER_PLAN = 20,
            OFFERING_1 = 21,
            OFFERING_2 = 22,
            POINT_OF_COLLECTION_1 = 23,
            POINT_OF_COLLECTION_2 = 24,
            PURIFICATION = 25,
            REFLECT_SHOT_1 = 26,
            REFLECT_SHOT_2 = 27,
            REFLECT_SHOT_3 = 28,
            REFLECT_SHOT_4 = 29,
            SCORCHED_EARTH_1 = 30,
            SCORCHED_EARTH_2 = 31,
            SEVEN_STAR_SWORD = 32,
            SPELL_ASSIST_1 = 33,
            SPELL_ASSIST_2 = 34,
            SPIRIT_CAMERA = 35,
            SUPERNATURAL_BORDER = 36,
            TANUKI_LEAF = 37,
            UCHIDES_MALLET = 38,
            VOILE_1 = 39,
            VOILE_2 = 40;

}
